In [1]:
import pandas as pd

In [8]:
df_car = {
    'car': ['BMW', 'Volvo', None, 'Ford'],
    'price': [30000, 50000, 20000, 43000]
}
df_car = pd.DataFrame(df_car)
df_car

     car  price
0    BMW  30000
1  Volvo  50000
2   None  20000
3   Ford  43000

In [9]:
df_car.head()

     car  price
0    BMW  30000
1  Volvo  50000
2   None  20000
3   Ford  43000

In [10]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   car     3 non-null      object
 1   price   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [11]:
df_car.isnull()

     car  price
0  False  False
1  False  False
2   True  False
3  False  False

In [13]:
print(df_car.loc[1])

car      Volvo
price    50000
Name: 1, dtype: object

In [15]:
print(df_car.loc[[0, 2]])

    car  price
0   BMW  30000
2  None  20000

In [16]:
df_training = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}
df_training = pd.DataFrame(df_training, index=['Monday', 'Tuesday', 'Wednesday'])
df_training.head()

           calories  duration
Monday          420        50
Tuesday         380        40
Wednesday       390        45

In [17]:
print(df_training.loc['Monday'])

calories    420
duration     50
Name: Monday, dtype: int64

In [18]:
df_training = {
    'calories': [420, 380, None, 390, None],
    'duration': [50, 40, 42, 45, None]
}
df_training = pd.DataFrame(df_training)
df_training

   calories  duration
0     420.0      50.0
1     380.0      40.0
2       NaN      42.0
3     390.0      45.0
4       NaN       NaN

In [19]:
df_training_cleaned = df_training.dropna()
df_training_cleaned

   calories  duration
0     420.0      50.0
1     380.0      40.0
3     390.0      45.0

In [21]:
df_training_cleaned.reset_index(inplace=True)
df_training_cleaned

   index  calories  duration
0      0     420.0      50.0
1      1     380.0      40.0
2      3     390.0      45.0

In [22]:
df_training_cleaned = df_training.fillna(0)
df_training_cleaned

   calories  duration
0     420.0      50.0
1     380.0      40.0
2       0.0      42.0
3     390.0      45.0
4       0.0       0.0

In [24]:
df_training = {
    'calories': [420, 380, 380, 390, None],
    'duration': [50, 40, 40, 45, None]
}
df_training = pd.DataFrame(df_training)
df_training

   calories  duration
0     420.0      50.0
1     380.0      40.0
2     380.0      40.0
3     390.0      45.0
4       NaN       NaN

In [25]:
print(df_training.duplicated())

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [27]:
df_training_unique = df_training.drop_duplicates().reset_index(drop=True)
df_training_unique

   calories  duration
0     420.0      50.0
1     380.0      40.0
2     390.0      45.0
3       NaN       NaN

In [28]:
df_car = {
    'car': ['BMW', 'Volvo', None, 'Ford'],
    'price': [30000, 50000, 20000, 43000]
}
df_car = pd.DataFrame(df_car)
df_car['car']

0      BMW
1    Volvo
2     None
3     Ford
Name: car, dtype: object

In [29]:
df_car['car'] = df_car['car'].fillna('Unknown Car')
df_car

           car  price
0          BMW  30000
1        Volvo  50000
2  Unknown Car  20000
3         Ford  43000

In [30]:
avg_price = df_car['price'].mean()
min_price = df_car['price'].min()
max_price = df_car['price'].max()
print(f'Avg = {avg_price}, Min = {min_price}, Max = {max_price}')

Avg = 35750.0, Min = 20000, Max = 50000

In [33]:
df_hr = pd.DataFrame({
    'employee': ['Bob', 'Jake', 'Lisa', 'Sue', 'David', 'Eva'],
    'dept': ['Accounting', 'Engineering', 'Engineering', 'HR', 'HR', 'Accounting'],
    'salary': [2000, 3000, 2500, 2400, 5000, 4000]
})
df_hr

  employee         dept  salary
0      Bob   Accounting    2000
1     Jake  Engineering    3000
2     Lisa  Engineering    2500
3      Sue           HR    2400
4    David           HR    5000
5      Eva   Accounting    4000

In [35]:
df_dept = df_hr.groupby('dept')
print(df_dept['salary'].mean())

dept
Accounting     3000.0
Engineering    2750.0
HR             3700.0
Name: salary, dtype: float64

In [36]:
print(df_dept['salary'].sum())

dept
Accounting     6000
Engineering    5500
HR             7400
Name: salary, dtype: int64

In [37]:
print(df_dept['salary'].min())

dept
Accounting     2000
Engineering    2500
HR             2400
Name: salary, dtype: int64

In [39]:
df_hr['Bonus'] = [200, 300, 150, 220, 500, 400]
df_hr

  employee         dept  salary  Bonus
0      Bob   Accounting    2000    200
1     Jake  Engineering    3000    300
2     Lisa  Engineering    2500    150
3      Sue           HR    2400    220
4    David           HR    5000    500
5      Eva   Accounting    4000    400

In [40]:
df_hr.drop('Bonus', axis=1, inplace=True)
df_hr

  employee         dept  salary
0      Bob   Accounting    2000
1     Jake  Engineering    3000
2     Lisa  Engineering    2500
3      Sue           HR    2400
4    David           HR    5000
5      Eva   Accounting    4000

In [41]:
df_hr.loc[4, 'salary'] = 4500
df_hr

  employee         dept  salary
0      Bob   Accounting    2000
1     Jake  Engineering    3000
2     Lisa  Engineering    2500
3      Sue           HR    2400
4    David           HR    4500
5      Eva   Accounting    4000

In [43]:
df_hr_sorted = df_hr.sort_values(by='salary', ascending=False)
df_hr_sorted

  employee         dept  salary
4    David           HR    4500
5      Eva   Accounting    4000
1     Jake  Engineering    3000
2     Lisa  Engineering    2500
3      Sue           HR    2400
0      Bob   Accounting    2000

In [44]:
df_training = pd.read_csv('datab7.csv')
df_training.head()

   Duration  Pulse  Maxpulse  Calories
0      60.0  110.0     130.0     409.1
1      60.0  117.0     145.0     479.0
2      60.0  103.0     135.0     340.0
3      45.0  109.0     175.0     282.4
4      45.0    NaN     148.0     406.0

In [45]:
df_training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  170 non-null    float64
 1   Pulse     171 non-null    float64
 2   Maxpulse  171 non-null    float64
 3   Calories  167 non-null    float64
dtypes: float64(4)
memory usage: 5.5 KB

In [46]:
df_training.isnull().sum()

Duration    2
Pulse       1
Maxpulse    1
Calories    5
dtype: int64

In [47]:
mean_cal = df_training['Calories'].mean()
df_training['Calories'].fillna(mean_cal, inplace=True)
df_training.isnull().sum()

/tmp/ipykernel_705/2232111465.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_training['Calories'].fillna(mean_cal, inplace=True)

Duration    2
Pulse       1
Maxpulse    1
Calories    0
dtype: int64

In [48]:
df_training.dropna(inplace=True)
df_training.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [49]:
df_training.describe()

         Duration       Pulse    Maxpulse     Calories
count  168.000000  168.000000  168.000000   168.000000
mean    64.136905  107.488095  134.244048   375.894768
std     42.384033   14.538402   16.496596   263.073280
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   252.725000
50%     60.000000  105.000000  131.000000   320.700000
75%     60.000000  111.000000  143.000000   383.100000
max    300.000000  159.000000  184.000000  1860.400000

In [50]:
df_training = pd.read_csv('datab7.csv')
df_training.isnull().sum()

Duration    2
Pulse       1
Maxpulse    1
Calories    5
dtype: int64

In [53]:
df_training['Duration'].fillna(df_training['Duration'].min(), inplace=True)
df_training['Pulse'].fillna(df_training['Pulse'].max(), inplace=True)
df_training['Maxpulse'].fillna(df_training['Maxpulse'].mean(), inplace=True)
df_training['Calories'].fillna(df_training['Calories'].median(), inplace=True)
df_training.isnull().sum()

/tmp/ipykernel_705/1437404192.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_training['Duration'].fillna(df_training['Duration'].min(), inplace=True)
/tmp/ipykernel_705/1437404192.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_training['Pulse'].fillna(df_training['Pulse'].max(), inplace=True)
/tmp/ipykernel_705/1437404192.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_training['Maxpulse'].fillna(df_training['Maxpulse'].mean(), inplace=True)

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [58]:
print(sorted([int(n) for n in df_training['Duration'].unique()]))

[15, 20, 25, 30, 45, 60, 75, 80, 90, 120, 150, 160, 180, 210, 270, 300]

In [62]:
print(df_training['Duration'].mean())

63.43023255813954

In [59]:
# Tính trung bình calories theo thời gian tập luyện
df_training_duration = df_training.groupby('Duration')
print(df_training_duration['Calories'].mean())

Duration
15.0      224.425000
20.0      151.600000
25.0      244.200000
30.0      192.125000
45.0      274.017647
60.0      339.003750
75.0      323.733333
80.0      643.100000
90.0      541.800000
120.0     666.833333
150.0     939.400000
160.0     943.700000
180.0     733.600000
210.0    1618.200000
270.0    1729.000000
300.0    1500.200000
Name: Calories, dtype: float64

In [60]:
print(df_training_duration['Pulse'].mean())

Duration
15.0     107.750000
20.0     125.000000
25.0     152.000000
30.0     109.812500
45.0     108.411765
60.0     106.187500
75.0     121.666667
80.0     123.000000
90.0      93.750000
120.0    100.000000
150.0    101.500000
160.0    109.500000
180.0     93.666667
210.0    122.500000
270.0    100.000000
300.0    108.000000
Name: Pulse, dtype: float64

In [61]:
print(df_training_duration['Maxpulse'].mean())

Duration
15.0     126.750000
20.0     146.000000
25.0     168.000000
30.0     137.000000
45.0     133.000000
60.0     133.354020
75.0     150.000000
80.0     146.000000
90.0     116.375000
120.0    139.000000
150.0    130.250000
160.0    136.000000
180.0    125.666667
210.0    172.000000
270.0    131.000000
300.0    143.000000
Name: Maxpulse, dtype: float64

In [63]:
def get_strength(duration):
  mean_duration = df_training['Duration'].mean()
  if duration > mean_duration:
    return 'Strong'
  else:
    return 'Weak'

In [64]:
print(get_strength(80))

Strong

In [65]:
print(get_strength(60))

Weak

In [66]:
strength_col = df_training['Duration'].apply(get_strength)
strength_col

0        Weak
1        Weak
2        Weak
3        Weak
4        Weak
        ...
167      Weak
168      Weak
169    Strong
170    Strong
171    Strong
Name: Duration, Length: 172, dtype: object

In [67]:
df_training['Strength'] = strength_col
df_training

     Duration  Pulse  Maxpulse  Calories Strength
0        60.0  110.0     130.0     409.1     Weak
1        60.0  117.0     145.0     479.0     Weak
2        60.0  103.0     135.0     340.0     Weak
3        45.0  109.0     175.0     282.4     Weak
4        45.0  159.0     148.0     406.0     Weak
..        ...    ...       ...       ...      ...
167      60.0  110.0     145.0     300.0     Weak
168      60.0  115.0     145.0     310.2     Weak
169      75.0  120.0     150.0     320.4   Strong
170      75.0  120.0     150.0     320.4   Strong
171      75.0  125.0     150.0     330.4   Strong

[172 rows x 5 columns]

In [68]:
df_training = pd.read_csv('datab7.csv')
df_training.dropna(inplace=True)
df_training.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [69]:
md = df_training['Duration'].mean()
df_training['Strength'] = df_training['Duration'].apply(lambda d: 'Strong' if d > md else 'Weak')
df_training

     Duration  Pulse  Maxpulse  Calories Strength
0        60.0  110.0     130.0     409.1     Weak
1        60.0  117.0     145.0     479.0     Weak
2        60.0  103.0     135.0     340.0     Weak
3        45.0  109.0     175.0     282.4     Weak
5        60.0  102.0     127.0     300.0     Weak
..        ...    ...       ...       ...      ...
167      60.0  110.0     145.0     300.0     Weak
168      60.0  115.0     145.0     310.2     Weak
169      75.0  120.0     150.0     320.4   Strong
170      75.0  120.0     150.0     320.4   Strong
171      75.0  125.0     150.0     330.4   Strong

[163 rows x 5 columns]

In [70]:
import random as rd

numbers = rd.sample(range(1, 100), 15)
print(numbers)

[2, 92, 78, 10, 35, 88, 97, 36, 58, 6, 40, 66, 82, 83, 24]

In [71]:
evens = [n for n in numbers if n % 2 == 0]
print(evens)

[2, 92, 78, 10, 88, 36, 58, 6, 40, 66, 82, 24]

In [72]:
odds = [n for n in numbers if n % 2 == 1]
print(odds)

[35, 97, 83]