In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    {
        "age": [25, 43, 26],
        "orders": [12, 4, 11],
        "payment": [3.5, 9.0, 3.8]
    }
)

In [3]:
df

   age  orders  payment
0   25      12      3.5
1   43       4      9.0
2   26      11      3.8

In [4]:
X = df.values
xa = X[0]
print(X)
print(xa)

[[25.  12.   3.5]
 [43.   4.   9. ]
 [26.  11.   3.8]]
[25.  12.   3.5]

In [5]:
xb = X[2]
print(xb)

[26.  11.   3.8]

In [6]:
xm = 0.5 * (xa + xb)
print(f'Customer A: {xa}')
print(f'Customer B: {xb}')
print(f'Midpoint: {xm}')

Customer A: [25.  12.   3.5]
Customer B: [26.  11.   3.8]
Midpoint: [25.5  11.5   3.65]

In [7]:
print(f'Centroid = {X.mean(axis=0)}')

Centroid = [31.33333333  9.          5.43333333]

In [8]:
print(f'Differnce between A and B: {xa - xb}')

Differnce between A and B: [-1.   1.  -0.3]

In [10]:
v = np.array([3, 4])
print(f'||v||_2 = {np.linalg.norm(v)}')
print(f'||v||_1 = {np.linalg.norm(v, ord=1)}')
print(f'||v||_inf = {np.linalg.norm(v, ord=np.inf)}')

||v||_2 = 5.0
||v||_1 = 7.0
||v||_inf = 4.0

In [20]:
df_raw = np.array([
    [25, 10_000_000],
    [26, 15_000_000],
    [55, 10_500_000]
])
labels = ['John', 'Paul', 'Mike']

In [17]:
def d(x, y):
  return np.linalg.norm(x - y)

In [21]:
# Tính khoảng cách giữa John và Paul
d_jp = d(df_raw[0], df_raw[1])
d_jm = d(df_raw[0], df_raw[2])
d_pm = d(df_raw[1], df_raw[2])
print(f'John - Paul: {d_jp}')
print(f'John - Mike: {d_jm}')
print(f'Paul - Mike: {d_pm}')

John - Paul: 5000000.0000001
John - Mike: 500000.0009
Paul - Mike: 4500000.000093444

In [22]:
Z = (df_raw - df_raw.mean(axis=0)) / df_raw.std(axis=0)
print(Z, Z.mean(axis=0), Z.std(axis=0))

[[-0.74274138 -0.81537425]
 [-0.67086318  1.4083737 ]
 [ 1.41360456 -0.59299945]] [-2.22044605e-16 -2.96059473e-16] [1. 1.]

In [23]:
print(f'John - Paul: {d(Z[0], Z[1])}')
print(f'John - Mike: {d(Z[0], Z[2])}')
print(f'Paul - Mike: {d(Z[1], Z[2])}')

John - Paul: 2.2249093061000655
John - Mike: 2.167781892535938
Paul - Mike: 2.8897232127009387

In [25]:
df_customers = pd.DataFrame(
    {
        "age": [30, 45, 22, 38],
        "payment": [5.0, 8.2, 2.1, 6.6],
        "city": ['Hanoi', 'Danang', 'Cantho', 'Hanoi']
    }
)

In [27]:
df_customers_encode = pd.get_dummies(df_customers, dtype=int)
df_customers_encode

   age  payment  city_Cantho  city_Danang  city_Hanoi
0   30      5.0            0            0           1
1   45      8.2            0            1           0
2   22      2.1            1            0           0
3   38      6.6            0            0           1

In [28]:
df = pd.DataFrame(
    {
        "age": [25, 43, 26],
        "orders": [12, 4, 11],
        "payment": [3.5, 9.0, 3.8]
    },
    index=['John', 'Paul', 'Mike']
)

In [29]:
names = list(df.index)
Dmat = np.array([[d(df.loc[names[i]], df.loc[names[j]]) for j in range(3)] for i in range(3)])
print(Dmat)

[[ 0.         20.45116134  1.44568323]
 [20.45116134  0.         19.10601999]
 [ 1.44568323 19.10601999  0.        ]]

In [32]:
# Anna
Anna = [24, 13, 3.2]
# Anna gần với khách hàng nào nhất?

In [30]:
print(X)

[[25.  12.   3.5]
 [43.   4.   9. ]
 [26.  11.   3.8]]

In [33]:
for i in range(3):
  print(f'{names[i]} - Anna: {d(X[i], Anna)}')

John - Anna: 1.445683229480096
Paul - Anna: 21.809172382279893
Mike - Anna: 2.891366458960192