In [32]:
import numpy as np
import pandas as pd

In [33]:
df = pd.DataFrame({'Grade': np.random.randint(50, 100, size=1000)})
df.head()

   Grade
0     74
1     80
2     78
3     61
4     59

In [34]:
df.describe()

             Grade
count  1000.000000
mean     75.494000
std      14.448416
min      50.000000
25%      63.000000
50%      77.000000
75%      88.000000
max      99.000000

In [35]:
# Lấy mẫu ngẫu nhiên
df_sample = df.sample(n=100, random_state=10)
df_sample.describe()

            Grade
count  100.000000
mean    75.400000
std     15.115047
min     50.000000
25%     60.000000
50%     76.500000
75%     87.750000
max     99.000000

In [36]:
df['Gender'] = np.random.choice(['Male', 'Female'], size=1000)
df.head()

   Grade  Gender
0     74    Male
1     80    Male
2     78    Male
3     61  Female
4     59    Male

In [37]:
df_sample = df.sample(n=100, random_state=10)
df_sample.head()

     Grade  Gender
841     93    Male
956     91  Female
544     80    Male
173     60  Female
759     60  Female

In [38]:
print(f'Số lượng Male tổng thể: {len(df[df["Gender"] == "Male"])}')
print(f'Số lượng Female tổng thể: {len(df[df["Gender"] == "Female"])}')
print(f'Số lượng Male mẫu: {len(df_sample[df_sample["Gender"] == "Male"])}')
print(f'Số lượng Female mẫu: {len(df_sample[df_sample["Gender"] == "Female"])}')

Số lượng Male tổng thể: 504
Số lượng Female tổng thể: 496
Số lượng Male mẫu: 47
Số lượng Female mẫu: 53

In [39]:
df_male = df[df["Gender"] == "Male"]        # tầng nam
df_female = df[df["Gender"] == "Female"]    # tầng nữ
df_male_sample = df_male.sample(n=50)       # lấy ngẫu nhiên 50 nam
df_female_sample = df_female.sample(n=50)   # lấy ngẫu nhiên 50 nữ
df_sample_groups = pd.concat([df_male_sample, df_female_sample])
print(f'Số lượng Male mẫu: {len(df_sample_groups[df_sample_groups["Gender"] == "Male"])}')
print(f'Số lượng Female mẫu: {len(df_sample_groups[df_sample_groups["Gender"] == "Female"])}')

Số lượng Male mẫu: 50
Số lượng Female mẫu: 50

In [40]:
df_sample_groups = df.groupby('Gender').apply(lambda x: x.sample(n=50, random_state=10))
print(f'Số lượng Male mẫu: {len(df_sample_groups[df_sample_groups["Gender"] == "Male"])}')
print(f'Số lượng Female mẫu: {len(df_sample_groups[df_sample_groups["Gender"] == "Female"])}')

Số lượng Male mẫu: 50
Số lượng Female mẫu: 50

/tmp/ipykernel_2586/232018711.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_sample_groups = df.groupby('Gender').apply(lambda x: x.sample(n=50, random_state=10))

In [41]:
n = 100
step = len(df) // n
df_sample_step = df[::step]
df_sample_step.head()

    Grade  Gender
0      74    Male
10     55  Female
20     82  Female
30     55    Male
40     55    Male

In [42]:
df['School'] = np.random.choice(
    [
        'ĐH Bách Khoa', 'ĐH Kinh tế', 'ĐH FPT', 'ĐH Xây dựng', 'ĐH Thương mại', 'ĐH Y', 'ĐH Công nghiệp', 'ĐH Giao thông',
        'ĐH Thủy lợi', 'ĐH Sư phạm'
    ],
    size=len(df)
)

In [43]:
df.head()

   Grade  Gender          School
0     74    Male     ĐH Thủy lợi
1     80    Male            ĐH Y
2     78    Male  ĐH Công nghiệp
3     61  Female            ĐH Y
4     59    Male  ĐH Công nghiệp

In [44]:
schools = ['ĐH Bách Khoa', 'ĐH Kinh tế', 'ĐH FPT']
df_sample_cluster = df[df['School'].isin(schools)]
df_sample_cluster.head()

    Grade  Gender        School
5      74  Female  ĐH Bách Khoa
8      57    Male  ĐH Bách Khoa
13     91    Male        ĐH FPT
17     72    Male    ĐH Kinh tế
18     67  Female        ĐH FPT